# Generated by Django 3.2.13 on 2022-05-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.veiculo'),
        ),
    ]
