# Generated by Django 3.2.13 on 2022-05-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220516_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosaida',
            name='observacoes',
            field=models.TextField(default='Defauet'),
        ),
    ]
