# Generated by Django 3.2.13 on 2022-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_registrosaida_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('d', 'Disponivel'), ('i', 'Indisponivel'), ('m', 'Manuntencao')], default=1, max_length=1),
        ),
    ]
