# Generated by Django 3.2.13 on 2022-05-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_veiculo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='hodometro_atual',
        ),
    ]
